// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(DarkfiMobileFfiFFI)
import DarkfiMobileFfiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_darkfi_mobile_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_darkfi_mobile_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDarkfiMobileFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol DarkfiWalletHandleProtocol: AnyObject, Sendable {
    
    func broadcastTransfer(txBytes: [UInt8], paymentMemo: String?, recipientAddress: String?) throws  -> String
    
    func buildTransfer(recipientAddress: String, amount: String, tokenId: String?, paymentMemo: String?) throws  -> [UInt8]
    
    func confirmedBalanceAtomic() throws  -> Int64
    
    func estimateTransferFee(recipientAddress: String, amount: String, tokenId: String?, paymentMemo: String?) throws  -> Int64
    
    func generateNewAddress() throws  -> String
    
    func getProposal(proposalBullaB58: String) throws  -> DrkDaoProposalDetail
    
    func listAddresses() throws  -> [String]
    
    func listDaos() throws  -> [DrkDaoSummary]
    
    func listProposals(daoName: String?) throws  -> [DrkDaoProposalSummary]
    
    func listTokenBalances() throws  -> [DrkTokenBalance]
    
    func listTransactions() throws  -> [DrkTransactionRecord]
    
    func primaryDepositAddress() throws  -> String
    
    func refreshNow() throws  -> DrkSyncSnapshot
    
    func syncSnapshot() throws  -> DrkSyncSnapshot
    
    func transactionPaymentMemo(txHash: String) throws  -> String?
    
    func transactionRecipient(txHash: String) throws  -> String?
    
}
open class DarkfiWalletHandle: DarkfiWalletHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_darkfi_mobile_ffi_fn_clone_darkfiwallethandle(self.handle, $0) }
    }
public convenience init(config: DrkBootstrapConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_constructor_darkfiwallethandle_new(
        FfiConverterTypeDrkBootstrapConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_darkfi_mobile_ffi_fn_free_darkfiwallethandle(handle, $0) }
    }

    

    
open func broadcastTransfer(txBytes: [UInt8], paymentMemo: String?, recipientAddress: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_broadcast_transfer(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt8.lower(txBytes),
        FfiConverterOptionString.lower(paymentMemo),
        FfiConverterOptionString.lower(recipientAddress),$0
    )
})
}
    
open func buildTransfer(recipientAddress: String, amount: String, tokenId: String?, paymentMemo: String?)throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_build_transfer(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(recipientAddress),
        FfiConverterString.lower(amount),
        FfiConverterOptionString.lower(tokenId),
        FfiConverterOptionString.lower(paymentMemo),$0
    )
})
}
    
open func confirmedBalanceAtomic()throws  -> Int64  {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_confirmed_balance_atomic(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func estimateTransferFee(recipientAddress: String, amount: String, tokenId: String?, paymentMemo: String?)throws  -> Int64  {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_estimate_transfer_fee(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(recipientAddress),
        FfiConverterString.lower(amount),
        FfiConverterOptionString.lower(tokenId),
        FfiConverterOptionString.lower(paymentMemo),$0
    )
})
}
    
open func generateNewAddress()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_generate_new_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getProposal(proposalBullaB58: String)throws  -> DrkDaoProposalDetail  {
    return try  FfiConverterTypeDrkDaoProposalDetail_lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_get_proposal(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(proposalBullaB58),$0
    )
})
}
    
open func listAddresses()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_list_addresses(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listDaos()throws  -> [DrkDaoSummary]  {
    return try  FfiConverterSequenceTypeDrkDaoSummary.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_list_daos(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listProposals(daoName: String?)throws  -> [DrkDaoProposalSummary]  {
    return try  FfiConverterSequenceTypeDrkDaoProposalSummary.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_list_proposals(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(daoName),$0
    )
})
}
    
open func listTokenBalances()throws  -> [DrkTokenBalance]  {
    return try  FfiConverterSequenceTypeDrkTokenBalance.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_list_token_balances(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func listTransactions()throws  -> [DrkTransactionRecord]  {
    return try  FfiConverterSequenceTypeDrkTransactionRecord.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_list_transactions(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func primaryDepositAddress()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_primary_deposit_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func refreshNow()throws  -> DrkSyncSnapshot  {
    return try  FfiConverterTypeDrkSyncSnapshot_lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_refresh_now(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func syncSnapshot()throws  -> DrkSyncSnapshot  {
    return try  FfiConverterTypeDrkSyncSnapshot_lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_sync_snapshot(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func transactionPaymentMemo(txHash: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_transaction_payment_memo(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(txHash),$0
    )
})
}
    
open func transactionRecipient(txHash: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_method_darkfiwallethandle_transaction_recipient(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(txHash),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDarkfiWalletHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DarkfiWalletHandle

    public static func lift(_ handle: UInt64) throws -> DarkfiWalletHandle {
        return DarkfiWalletHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DarkfiWalletHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DarkfiWalletHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DarkfiWalletHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDarkfiWalletHandle_lift(_ handle: UInt64) throws -> DarkfiWalletHandle {
    return try FfiConverterTypeDarkfiWalletHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDarkfiWalletHandle_lower(_ value: DarkfiWalletHandle) -> UInt64 {
    return FfiConverterTypeDarkfiWalletHandle.lower(value)
}




public struct DmKeypair: Equatable, Hashable {
    public var secretB58: String
    public var publicB58: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretB58: String, publicB58: String) {
        self.secretB58 = secretB58
        self.publicB58 = publicB58
    }

    

    
}

#if compiler(>=6)
extension DmKeypair: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDmKeypair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DmKeypair {
        return
            try DmKeypair(
                secretB58: FfiConverterString.read(from: &buf), 
                publicB58: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DmKeypair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretB58, into: &buf)
        FfiConverterString.write(value.publicB58, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDmKeypair_lift(_ buf: RustBuffer) throws -> DmKeypair {
    return try FfiConverterTypeDmKeypair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDmKeypair_lower(_ value: DmKeypair) -> RustBuffer {
    return FfiConverterTypeDmKeypair.lower(value)
}


public struct DrkBootstrapConfig: Equatable, Hashable {
    public var network: String
    public var mnemonic: [String]
    public var walletDbPath: String
    public var cachePath: String
    public var walletPass: String
    public var darkfidEndpointUrl: String
    public var birthdayHeight: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(network: String, mnemonic: [String], walletDbPath: String, cachePath: String, walletPass: String, darkfidEndpointUrl: String, birthdayHeight: Int64) {
        self.network = network
        self.mnemonic = mnemonic
        self.walletDbPath = walletDbPath
        self.cachePath = cachePath
        self.walletPass = walletPass
        self.darkfidEndpointUrl = darkfidEndpointUrl
        self.birthdayHeight = birthdayHeight
    }

    

    
}

#if compiler(>=6)
extension DrkBootstrapConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkBootstrapConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkBootstrapConfig {
        return
            try DrkBootstrapConfig(
                network: FfiConverterString.read(from: &buf), 
                mnemonic: FfiConverterSequenceString.read(from: &buf), 
                walletDbPath: FfiConverterString.read(from: &buf), 
                cachePath: FfiConverterString.read(from: &buf), 
                walletPass: FfiConverterString.read(from: &buf), 
                darkfidEndpointUrl: FfiConverterString.read(from: &buf), 
                birthdayHeight: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DrkBootstrapConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.network, into: &buf)
        FfiConverterSequenceString.write(value.mnemonic, into: &buf)
        FfiConverterString.write(value.walletDbPath, into: &buf)
        FfiConverterString.write(value.cachePath, into: &buf)
        FfiConverterString.write(value.walletPass, into: &buf)
        FfiConverterString.write(value.darkfidEndpointUrl, into: &buf)
        FfiConverterInt64.write(value.birthdayHeight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkBootstrapConfig_lift(_ buf: RustBuffer) throws -> DrkBootstrapConfig {
    return try FfiConverterTypeDrkBootstrapConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkBootstrapConfig_lower(_ value: DrkBootstrapConfig) -> RustBuffer {
    return FfiConverterTypeDrkBootstrapConfig.lower(value)
}


public struct DrkDaoProposalDetail: Equatable, Hashable {
    public var proposalBullaB58: String
    public var daoName: String
    public var daoBullaB58: String
    public var authCallCount: UInt32
    public var durationBlockwindows: UInt64
    public var creationBlockwindow: UInt64
    public var mintHeight: Int64
    public var execHeight: Int64
    public var isExecuted: Bool
    public var summaryLine: String
    public var proposeTxHash: String?
    public var execTxHash: String?
    public var hasPlaintextData: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proposalBullaB58: String, daoName: String, daoBullaB58: String, authCallCount: UInt32, durationBlockwindows: UInt64, creationBlockwindow: UInt64, mintHeight: Int64, execHeight: Int64, isExecuted: Bool, summaryLine: String, proposeTxHash: String?, execTxHash: String?, hasPlaintextData: Bool) {
        self.proposalBullaB58 = proposalBullaB58
        self.daoName = daoName
        self.daoBullaB58 = daoBullaB58
        self.authCallCount = authCallCount
        self.durationBlockwindows = durationBlockwindows
        self.creationBlockwindow = creationBlockwindow
        self.mintHeight = mintHeight
        self.execHeight = execHeight
        self.isExecuted = isExecuted
        self.summaryLine = summaryLine
        self.proposeTxHash = proposeTxHash
        self.execTxHash = execTxHash
        self.hasPlaintextData = hasPlaintextData
    }

    

    
}

#if compiler(>=6)
extension DrkDaoProposalDetail: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkDaoProposalDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkDaoProposalDetail {
        return
            try DrkDaoProposalDetail(
                proposalBullaB58: FfiConverterString.read(from: &buf), 
                daoName: FfiConverterString.read(from: &buf), 
                daoBullaB58: FfiConverterString.read(from: &buf), 
                authCallCount: FfiConverterUInt32.read(from: &buf), 
                durationBlockwindows: FfiConverterUInt64.read(from: &buf), 
                creationBlockwindow: FfiConverterUInt64.read(from: &buf), 
                mintHeight: FfiConverterInt64.read(from: &buf), 
                execHeight: FfiConverterInt64.read(from: &buf), 
                isExecuted: FfiConverterBool.read(from: &buf), 
                summaryLine: FfiConverterString.read(from: &buf), 
                proposeTxHash: FfiConverterOptionString.read(from: &buf), 
                execTxHash: FfiConverterOptionString.read(from: &buf), 
                hasPlaintextData: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DrkDaoProposalDetail, into buf: inout [UInt8]) {
        FfiConverterString.write(value.proposalBullaB58, into: &buf)
        FfiConverterString.write(value.daoName, into: &buf)
        FfiConverterString.write(value.daoBullaB58, into: &buf)
        FfiConverterUInt32.write(value.authCallCount, into: &buf)
        FfiConverterUInt64.write(value.durationBlockwindows, into: &buf)
        FfiConverterUInt64.write(value.creationBlockwindow, into: &buf)
        FfiConverterInt64.write(value.mintHeight, into: &buf)
        FfiConverterInt64.write(value.execHeight, into: &buf)
        FfiConverterBool.write(value.isExecuted, into: &buf)
        FfiConverterString.write(value.summaryLine, into: &buf)
        FfiConverterOptionString.write(value.proposeTxHash, into: &buf)
        FfiConverterOptionString.write(value.execTxHash, into: &buf)
        FfiConverterBool.write(value.hasPlaintextData, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoProposalDetail_lift(_ buf: RustBuffer) throws -> DrkDaoProposalDetail {
    return try FfiConverterTypeDrkDaoProposalDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoProposalDetail_lower(_ value: DrkDaoProposalDetail) -> RustBuffer {
    return FfiConverterTypeDrkDaoProposalDetail.lower(value)
}


public struct DrkDaoProposalSummary: Equatable, Hashable {
    public var proposalBullaB58: String
    public var daoName: String
    public var daoBullaB58: String
    public var authCallCount: UInt32
    public var durationBlockwindows: UInt64
    public var creationBlockwindow: UInt64
    public var mintHeight: Int64
    public var execHeight: Int64
    public var isExecuted: Bool
    public var summaryLine: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proposalBullaB58: String, daoName: String, daoBullaB58: String, authCallCount: UInt32, durationBlockwindows: UInt64, creationBlockwindow: UInt64, mintHeight: Int64, execHeight: Int64, isExecuted: Bool, summaryLine: String) {
        self.proposalBullaB58 = proposalBullaB58
        self.daoName = daoName
        self.daoBullaB58 = daoBullaB58
        self.authCallCount = authCallCount
        self.durationBlockwindows = durationBlockwindows
        self.creationBlockwindow = creationBlockwindow
        self.mintHeight = mintHeight
        self.execHeight = execHeight
        self.isExecuted = isExecuted
        self.summaryLine = summaryLine
    }

    

    
}

#if compiler(>=6)
extension DrkDaoProposalSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkDaoProposalSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkDaoProposalSummary {
        return
            try DrkDaoProposalSummary(
                proposalBullaB58: FfiConverterString.read(from: &buf), 
                daoName: FfiConverterString.read(from: &buf), 
                daoBullaB58: FfiConverterString.read(from: &buf), 
                authCallCount: FfiConverterUInt32.read(from: &buf), 
                durationBlockwindows: FfiConverterUInt64.read(from: &buf), 
                creationBlockwindow: FfiConverterUInt64.read(from: &buf), 
                mintHeight: FfiConverterInt64.read(from: &buf), 
                execHeight: FfiConverterInt64.read(from: &buf), 
                isExecuted: FfiConverterBool.read(from: &buf), 
                summaryLine: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DrkDaoProposalSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.proposalBullaB58, into: &buf)
        FfiConverterString.write(value.daoName, into: &buf)
        FfiConverterString.write(value.daoBullaB58, into: &buf)
        FfiConverterUInt32.write(value.authCallCount, into: &buf)
        FfiConverterUInt64.write(value.durationBlockwindows, into: &buf)
        FfiConverterUInt64.write(value.creationBlockwindow, into: &buf)
        FfiConverterInt64.write(value.mintHeight, into: &buf)
        FfiConverterInt64.write(value.execHeight, into: &buf)
        FfiConverterBool.write(value.isExecuted, into: &buf)
        FfiConverterString.write(value.summaryLine, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoProposalSummary_lift(_ buf: RustBuffer) throws -> DrkDaoProposalSummary {
    return try FfiConverterTypeDrkDaoProposalSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoProposalSummary_lower(_ value: DrkDaoProposalSummary) -> RustBuffer {
    return FfiConverterTypeDrkDaoProposalSummary.lower(value)
}


public struct DrkDaoSummary: Equatable, Hashable {
    public var name: String
    public var bullaB58: String
    public var govTokenId: String
    public var quorumDisplay: String
    public var proposerLimitDisplay: String
    public var approvalRatioPercent: Double
    public var mintHeight: Int64
    public var canPropose: Bool
    public var canVote: Bool
    public var canExec: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, bullaB58: String, govTokenId: String, quorumDisplay: String, proposerLimitDisplay: String, approvalRatioPercent: Double, mintHeight: Int64, canPropose: Bool, canVote: Bool, canExec: Bool) {
        self.name = name
        self.bullaB58 = bullaB58
        self.govTokenId = govTokenId
        self.quorumDisplay = quorumDisplay
        self.proposerLimitDisplay = proposerLimitDisplay
        self.approvalRatioPercent = approvalRatioPercent
        self.mintHeight = mintHeight
        self.canPropose = canPropose
        self.canVote = canVote
        self.canExec = canExec
    }

    

    
}

#if compiler(>=6)
extension DrkDaoSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkDaoSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkDaoSummary {
        return
            try DrkDaoSummary(
                name: FfiConverterString.read(from: &buf), 
                bullaB58: FfiConverterString.read(from: &buf), 
                govTokenId: FfiConverterString.read(from: &buf), 
                quorumDisplay: FfiConverterString.read(from: &buf), 
                proposerLimitDisplay: FfiConverterString.read(from: &buf), 
                approvalRatioPercent: FfiConverterDouble.read(from: &buf), 
                mintHeight: FfiConverterInt64.read(from: &buf), 
                canPropose: FfiConverterBool.read(from: &buf), 
                canVote: FfiConverterBool.read(from: &buf), 
                canExec: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DrkDaoSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.bullaB58, into: &buf)
        FfiConverterString.write(value.govTokenId, into: &buf)
        FfiConverterString.write(value.quorumDisplay, into: &buf)
        FfiConverterString.write(value.proposerLimitDisplay, into: &buf)
        FfiConverterDouble.write(value.approvalRatioPercent, into: &buf)
        FfiConverterInt64.write(value.mintHeight, into: &buf)
        FfiConverterBool.write(value.canPropose, into: &buf)
        FfiConverterBool.write(value.canVote, into: &buf)
        FfiConverterBool.write(value.canExec, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoSummary_lift(_ buf: RustBuffer) throws -> DrkDaoSummary {
    return try FfiConverterTypeDrkDaoSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkDaoSummary_lower(_ value: DrkDaoSummary) -> RustBuffer {
    return FfiConverterTypeDrkDaoSummary.lower(value)
}


public struct DrkSyncSnapshot: Equatable, Hashable {
    public var scannedBlocks: Int64
    public var chainTip: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(scannedBlocks: Int64, chainTip: Int64) {
        self.scannedBlocks = scannedBlocks
        self.chainTip = chainTip
    }

    

    
}

#if compiler(>=6)
extension DrkSyncSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkSyncSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkSyncSnapshot {
        return
            try DrkSyncSnapshot(
                scannedBlocks: FfiConverterInt64.read(from: &buf), 
                chainTip: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DrkSyncSnapshot, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.scannedBlocks, into: &buf)
        FfiConverterInt64.write(value.chainTip, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkSyncSnapshot_lift(_ buf: RustBuffer) throws -> DrkSyncSnapshot {
    return try FfiConverterTypeDrkSyncSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkSyncSnapshot_lower(_ value: DrkSyncSnapshot) -> RustBuffer {
    return FfiConverterTypeDrkSyncSnapshot.lower(value)
}


public struct DrkTokenBalance: Equatable, Hashable {
    public var tokenId: String
    public var displayLabel: String?
    public var balanceAtomic: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tokenId: String, displayLabel: String?, balanceAtomic: Int64) {
        self.tokenId = tokenId
        self.displayLabel = displayLabel
        self.balanceAtomic = balanceAtomic
    }

    

    
}

#if compiler(>=6)
extension DrkTokenBalance: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkTokenBalance: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkTokenBalance {
        return
            try DrkTokenBalance(
                tokenId: FfiConverterString.read(from: &buf), 
                displayLabel: FfiConverterOptionString.read(from: &buf), 
                balanceAtomic: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DrkTokenBalance, into buf: inout [UInt8]) {
        FfiConverterString.write(value.tokenId, into: &buf)
        FfiConverterOptionString.write(value.displayLabel, into: &buf)
        FfiConverterInt64.write(value.balanceAtomic, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkTokenBalance_lift(_ buf: RustBuffer) throws -> DrkTokenBalance {
    return try FfiConverterTypeDrkTokenBalance.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkTokenBalance_lower(_ value: DrkTokenBalance) -> RustBuffer {
    return FfiConverterTypeDrkTokenBalance.lower(value)
}


public struct DrkTransactionRecord: Equatable, Hashable {
    public var txHash: String
    public var status: String
    public var blockHeight: Int64
    public var feeAtomic: Int64
    public var isSent: Bool
    public var netValueAtomic: Int64
    public var contractSummary: String
    public var recipientAddress: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txHash: String, status: String, blockHeight: Int64, feeAtomic: Int64, isSent: Bool, netValueAtomic: Int64, contractSummary: String, recipientAddress: String?) {
        self.txHash = txHash
        self.status = status
        self.blockHeight = blockHeight
        self.feeAtomic = feeAtomic
        self.isSent = isSent
        self.netValueAtomic = netValueAtomic
        self.contractSummary = contractSummary
        self.recipientAddress = recipientAddress
    }

    

    
}

#if compiler(>=6)
extension DrkTransactionRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrkTransactionRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrkTransactionRecord {
        return
            try DrkTransactionRecord(
                txHash: FfiConverterString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                blockHeight: FfiConverterInt64.read(from: &buf), 
                feeAtomic: FfiConverterInt64.read(from: &buf), 
                isSent: FfiConverterBool.read(from: &buf), 
                netValueAtomic: FfiConverterInt64.read(from: &buf), 
                contractSummary: FfiConverterString.read(from: &buf), 
                recipientAddress: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DrkTransactionRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txHash, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterInt64.write(value.blockHeight, into: &buf)
        FfiConverterInt64.write(value.feeAtomic, into: &buf)
        FfiConverterBool.write(value.isSent, into: &buf)
        FfiConverterInt64.write(value.netValueAtomic, into: &buf)
        FfiConverterString.write(value.contractSummary, into: &buf)
        FfiConverterOptionString.write(value.recipientAddress, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkTransactionRecord_lift(_ buf: RustBuffer) throws -> DrkTransactionRecord {
    return try FfiConverterTypeDrkTransactionRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrkTransactionRecord_lower(_ value: DrkTransactionRecord) -> RustBuffer {
    return FfiConverterTypeDrkTransactionRecord.lower(value)
}


public enum DarkfiWalletNativeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case WalletNotInitialized(message: String)
    
    case InvalidBootstrapConfig(message: String)
    
    case NativeDrkUnavailable(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension DarkfiWalletNativeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDarkfiWalletNativeError: FfiConverterRustBuffer {
    typealias SwiftType = DarkfiWalletNativeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DarkfiWalletNativeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .WalletNotInitialized(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidBootstrapConfig(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .NativeDrkUnavailable(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DarkfiWalletNativeError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .WalletNotInitialized(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidBootstrapConfig(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .NativeDrkUnavailable(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDarkfiWalletNativeError_lift(_ buf: RustBuffer) throws -> DarkfiWalletNativeError {
    return try FfiConverterTypeDarkfiWalletNativeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDarkfiWalletNativeError_lower(_ value: DarkfiWalletNativeError) -> RustBuffer {
    return FfiConverterTypeDarkfiWalletNativeError.lower(value)
}




public protocol DarkircEventCallback: AnyObject, Sendable {
    
    func onMessage(channel: String, nick: String, message: String, timestampMs: UInt64) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDarkircEventCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceDarkircEventCallback = UniffiVTableCallbackInterfaceDarkircEventCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceDarkircEventCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface DarkircEventCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceDarkircEventCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface DarkircEventCallback: handle missing in uniffiClone")
            }
        },
        onMessage: { (
            uniffiHandle: UInt64,
            channel: RustBuffer,
            nick: RustBuffer,
            message: RustBuffer,
            timestampMs: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceDarkircEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessage(
                     channel: try FfiConverterString.lift(channel),
                     nick: try FfiConverterString.lift(nick),
                     message: try FfiConverterString.lift(message),
                     timestampMs: try FfiConverterUInt64.lift(timestampMs)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceDarkircEventCallback> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceDarkircEventCallback>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitDarkircEventCallback() {
    uniffi_darkfi_mobile_ffi_fn_init_callback_vtable_darkirceventcallback(UniffiCallbackInterfaceDarkircEventCallback.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceDarkircEventCallback {
    fileprivate static let handleMap = UniffiHandleMap<DarkircEventCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceDarkircEventCallback : FfiConverter {
    typealias SwiftType = DarkircEventCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceDarkircEventCallback_lift(_ handle: UInt64) throws -> DarkircEventCallback {
    return try FfiConverterCallbackInterfaceDarkircEventCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceDarkircEventCallback_lower(_ v: DarkircEventCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceDarkircEventCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceDarkircEventCallback: FfiConverterRustBuffer {
    typealias SwiftType = DarkircEventCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceDarkircEventCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceDarkircEventCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrkDaoProposalSummary: FfiConverterRustBuffer {
    typealias SwiftType = [DrkDaoProposalSummary]

    public static func write(_ value: [DrkDaoProposalSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrkDaoProposalSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DrkDaoProposalSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [DrkDaoProposalSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrkDaoProposalSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrkDaoSummary: FfiConverterRustBuffer {
    typealias SwiftType = [DrkDaoSummary]

    public static func write(_ value: [DrkDaoSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrkDaoSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DrkDaoSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [DrkDaoSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrkDaoSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrkTokenBalance: FfiConverterRustBuffer {
    typealias SwiftType = [DrkTokenBalance]

    public static func write(_ value: [DrkTokenBalance], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrkTokenBalance.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DrkTokenBalance] {
        let len: Int32 = try readInt(&buf)
        var seq = [DrkTokenBalance]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrkTokenBalance.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDrkTransactionRecord: FfiConverterRustBuffer {
    typealias SwiftType = [DrkTransactionRecord]

    public static func write(_ value: [DrkTransactionRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDrkTransactionRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DrkTransactionRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [DrkTransactionRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDrkTransactionRecord.read(from: &buf))
        }
        return seq
    }
}
public func bridgePing() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_bridge_ping($0
    )
})
}
public func bridgeVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_bridge_version($0
    )
})
}
public func chachaDecryptDm(mySecret: [UInt8], theirPublic: [UInt8], ciphertextB58: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_chacha_decrypt_dm(
        FfiConverterSequenceUInt8.lower(mySecret),
        FfiConverterSequenceUInt8.lower(theirPublic),
        FfiConverterString.lower(ciphertextB58),$0
    )
})
}
public func chachaEncryptDm(mySecret: [UInt8], theirPublic: [UInt8], plaintext: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_chacha_encrypt_dm(
        FfiConverterSequenceUInt8.lower(mySecret),
        FfiConverterSequenceUInt8.lower(theirPublic),
        FfiConverterString.lower(plaintext),$0
    )
})
}
public func darkircStatus() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_darkirc_status($0
    )
})
}
public func decodeChatEntropy(phrase: [String]) -> [UInt8]?  {
    return try!  FfiConverterOptionSequenceUInt8.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_decode_chat_entropy(
        FfiConverterSequenceString.lower(phrase),$0
    )
})
}
public func generateBip39ChatMnemonic() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_generate_bip39_chat_mnemonic($0
    )
})
}
public func generateDarkfiMnemonic() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_generate_darkfi_mnemonic($0
    )
})
}
public func generateDmKeypair() -> DmKeypair  {
    return try!  FfiConverterTypeDmKeypair_lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_generate_dm_keypair($0
    )
})
}
public func isArtiRunning() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_is_arti_running($0
    )
})
}
public func sendChatMessage(channel: String, nick: String, message: String)throws   {try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_send_chat_message(
        FfiConverterString.lower(channel),
        FfiConverterString.lower(nick),
        FfiConverterString.lower(message),$0
    )
}
}
public func startArtiProxy(socksPort: UInt16)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_start_arti_proxy(
        FfiConverterUInt16.lower(socksPort),$0
    )
})
}
public func startDarkirc(datastorePath: String, useTor: Bool, callback: DarkircEventCallback?)throws   {try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_start_darkirc(
        FfiConverterString.lower(datastorePath),
        FfiConverterBool.lower(useTor),
        FfiConverterOptionCallbackInterfaceDarkircEventCallback.lower(callback),$0
    )
}
}
public func stopArtiProxy()  {try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_stop_arti_proxy($0
    )
}
}
public func stopDarkirc()throws   {try rustCallWithError(FfiConverterTypeDarkfiWalletNativeError_lift) {
    uniffi_darkfi_mobile_ffi_fn_func_stop_darkirc($0
    )
}
}
public func validateDarkfiMnemonic(phrase: [String]) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_darkfi_mobile_ffi_fn_func_validate_darkfi_mnemonic(
        FfiConverterSequenceString.lower(phrase),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_darkfi_mobile_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_bridge_ping() != 23250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_bridge_version() != 4310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_chacha_decrypt_dm() != 31696) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_chacha_encrypt_dm() != 54760) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_darkirc_status() != 29954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_decode_chat_entropy() != 49247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_generate_bip39_chat_mnemonic() != 13350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_generate_darkfi_mnemonic() != 7911) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_generate_dm_keypair() != 60508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_is_arti_running() != 33624) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_send_chat_message() != 4769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_start_arti_proxy() != 13421) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_start_darkirc() != 38342) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_stop_arti_proxy() != 38081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_stop_darkirc() != 44306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_func_validate_darkfi_mnemonic() != 42375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_broadcast_transfer() != 37823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_build_transfer() != 40440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_confirmed_balance_atomic() != 48819) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_estimate_transfer_fee() != 27640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_generate_new_address() != 60300) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_get_proposal() != 62881) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_list_addresses() != 34533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_list_daos() != 26155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_list_proposals() != 62268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_list_token_balances() != 28349) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_list_transactions() != 40596) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_primary_deposit_address() != 18714) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_refresh_now() != 57567) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_sync_snapshot() != 34731) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_transaction_payment_memo() != 63542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkfiwallethandle_transaction_recipient() != 27939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_constructor_darkfiwallethandle_new() != 8185) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_darkfi_mobile_ffi_checksum_method_darkirceventcallback_on_message() != 46557) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDarkircEventCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDarkfiMobileFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all