// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockRange {
    /// Start height, inclusive
    #[prost(uint32, tag = "1")]
    pub start_height: u32,
    /// End height, inclusive
    #[prost(uint32, tag = "2")]
    pub end_height: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockHeight {
    #[prost(uint32, tag = "1")]
    pub height: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeightList {
    /// Sorted unique preferred; server sorts/dedups
    #[prost(uint32, repeated, tag = "1")]
    pub heights: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxHash {
    /// 32-byte blake3 transaction hash
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainTip {
    #[prost(uint32, tag = "1")]
    pub height: u32,
    /// 32-byte blake3 header hash
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    #[prost(uint32, tag = "4")]
    pub block_target: u32,
}
/// A compact representation of a DarkFi block, stripped of ZK proofs and
/// signatures. Contains only the data needed for wallet sync:
/// - Per-output: coin commitment, encrypted note, value/token commitments
/// - Per-input: nullifier (for spend detection)
/// - Block metadata: height, hash, previous hash, timestamp
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactBlock {
    #[prost(uint32, tag = "1")]
    pub height: u32,
    /// 32-byte blake3 header hash
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte blake3 previous header hash
    #[prost(bytes = "vec", tag = "3")]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    #[prost(message, repeated, tag = "5")]
    pub txs: ::prost::alloc::vec::Vec<CompactTx>,
}
/// A compact representation of a single transaction within a block.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactTx {
    /// 32-byte blake3 transaction hash
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// The Money contract outputs (coins + encrypted notes)
    #[prost(message, repeated, tag = "2")]
    pub outputs: ::prost::alloc::vec::Vec<CompactOutput>,
    /// Revealed nullifiers (each 32 bytes)
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub nullifiers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Fee paid by this transaction (if parseable)
    #[prost(uint64, tag = "4")]
    pub fee: u64,
}
/// A compact representation of a single transaction output.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactOutput {
    /// Coin commitment: Poseidon hash of CoinAttributes (32 bytes, pallas::Base)
    #[prost(bytes = "vec", tag = "1")]
    pub coin: ::prost::alloc::vec::Vec<u8>,
    /// AeadEncryptedNote: serialized (ephem_public + ciphertext)
    /// Clients trial-decrypt this with their secret key via DH + ChaCha20Poly1305
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_note: ::prost::alloc::vec::Vec<u8>,
    /// Pedersen commitment for value (33 bytes, compressed pallas::Point)
    #[prost(bytes = "vec", tag = "3")]
    pub value_commit: ::prost::alloc::vec::Vec<u8>,
    /// Commitment for token ID (32 bytes, pallas::Base)
    #[prost(bytes = "vec", tag = "4")]
    pub token_commit: ::prost::alloc::vec::Vec<u8>,
    /// FHE OMR clue byte array
    #[prost(bytes = "vec", tag = "5")]
    pub omr_clue: ::prost::alloc::vec::Vec<u8>,
    /// Recipient-encrypted OMR metadata (scheme + clue seed + user memo).
    /// Encrypted with recipient's pubkey via DH + ChaCha20Poly1305.
    /// LWD stores opaquely; cannot decrypt. Merged on block confirm.
    #[prost(bytes = "vec", tag = "6")]
    pub omr_metadata_enc: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NoteCommitmentUpdate {
    #[prost(uint32, tag = "1")]
    pub height: u32,
    /// New coin commitments added at this height (each 32 bytes)
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NullifierUpdate {
    #[prost(uint32, tag = "1")]
    pub height: u32,
    /// New nullifiers revealed at this height (each 32 bytes)
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub nullifiers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TreeState {
    #[prost(uint32, tag = "1")]
    pub height: u32,
    /// Serialized MerkleTree (DarkFi bridgetree format)
    #[prost(bytes = "vec", tag = "2")]
    pub tree_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawTransaction {
    /// Serialized DarkFi Transaction (darkfi-serial format)
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Optional FHE / UnifOMR clue for the payment output.
    #[prost(bytes = "vec", tag = "2")]
    pub omr_clue: ::prost::alloc::vec::Vec<u8>,
    /// Compact-block output index the clue applies to (payment output).
    /// Default 0. Change outputs must not receive the recipient clue.
    #[prost(uint32, tag = "3")]
    pub omr_clue_output_index: u32,
    /// Recipient-encrypted OMR metadata (scheme + clue seed + user memo).
    /// LWD stores opaquely and merges into CompactOutput.omr_metadata_enc on confirm.
    #[prost(bytes = "vec", tag = "4")]
    pub omr_metadata_enc: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmrClueRegistration {
    /// 32-byte blake3 transaction hash
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// FHE / UnifOMR clue bytes
    #[prost(bytes = "vec", tag = "2")]
    pub omr_clue: ::prost::alloc::vec::Vec<u8>,
    /// Output index (default 0 = payment output).
    #[prost(uint32, tag = "3")]
    pub omr_clue_output_index: u32,
    /// Recipient-encrypted OMR metadata.
    #[prost(bytes = "vec", tag = "4")]
    pub omr_metadata_enc: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendResponse {
    /// Transaction hash if successful
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// Error message if failed, empty string on success
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    /// Whether an attached OMR clue was accepted and stored (S22).
    /// false when the clue was empty, rejected by validation, or could not be stored.
    #[prost(bool, tag = "3")]
    pub clue_accepted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractId {
    /// Base58-encoded contract ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZkasResponse {
    #[prost(message, repeated, tag = "1")]
    pub bincodes: ::prost::alloc::vec::Vec<ZkasBincode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZkasBincode {
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub bincode: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightInfo {
    /// Server version string
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Chain identifier
    #[prost(string, tag = "2")]
    pub chain_name: ::prost::alloc::string::String,
    /// Current best block height
    #[prost(uint32, tag = "3")]
    pub block_height: u32,
    /// Block target time in seconds
    #[prost(uint32, tag = "4")]
    pub block_target: u32,
    /// Current difficulty (as string for big integer)
    #[prost(string, tag = "5")]
    pub difficulty: ::prost::alloc::string::String,
    /// Whether the server supports OMR detection
    #[prost(bool, tag = "6")]
    pub omr_supported: bool,
    /// Current best block hash
    #[prost(bytes = "vec", tag = "7")]
    pub best_block_hash: ::prost::alloc::vec::Vec<u8>,
    /// Backing node version string
    #[prost(string, tag = "8")]
    pub backend_version: ::prost::alloc::string::String,
    /// 32-byte Schnorr public key for GetCluePublicKey directory attestations.
    /// Clients verify ownership_proof against this key (not the payment key).
    #[prost(bytes = "vec", tag = "9")]
    pub directory_attest_pubkey: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmrDigestResponse {
    /// FHE encrypted digest containing the matching block heights.
    /// For multi-key requests: length-prefixed frames, one digest per key
    /// ([u32 LE len][digest]…), decrypted client-side with the matching key.
    /// The client decrypts this locally.
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_digest: ::prost::alloc::vec::Vec<u8>,
    /// Whether the digest covers the full requested range
    #[prost(bool, tag = "2")]
    pub complete: bool,
}
/// Client-streaming message for StreamDetectionKey.
/// The first chunk MUST carry the header fields (start/end height, key count).
/// Subsequent chunks carry raw detection key bytes.  Multiple keys are sent
/// sequentially: finish key 0's bytes, then key 1's bytes, etc.  Each key
/// boundary is indicated by `key_done = true` on the last chunk of that key.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectionKeyChunk {
    /// Only set on the first chunk (header).  Ignored on subsequent chunks.
    #[prost(uint32, tag = "1")]
    pub start_height: u32,
    #[prost(uint32, tag = "2")]
    pub end_height: u32,
    /// Expected number of detection keys that will follow (cap 16).
    #[prost(uint32, tag = "3")]
    pub num_keys: u32,
    /// Raw detection key bytes (partial or complete).
    /// Recommended chunk size: 1 MiB (1_048_576 bytes).
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Set to true on the last chunk of each individual key.  The server
    /// uses this to delimit multi-key uploads (key_done count must equal
    /// num_keys before processing begins).
    #[prost(bool, tag = "5")]
    pub key_done: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OmrCapabilities {
    /// Whether OMR is currently enabled and operational
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// Supported OMR scheme name ("unifomr" when enabled)
    #[prost(string, tag = "2")]
    pub scheme: ::prost::alloc::string::String,
    /// Server-side false positive rate (informational)
    #[prost(double, tag = "3")]
    pub false_positive_rate: f64,
    /// Maximum block range per digest request
    #[prost(uint32, tag = "4")]
    pub max_range_per_request: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentPubkey {
    /// 32-byte DarkFi payment public key
    #[prost(bytes = "vec", tag = "1")]
    pub payment_pubkey: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CluePublicKeyRegistration {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// Serialized UnifOMR RLWE public key (see unifomr::serialize_public_key)
    #[prost(bytes = "vec", tag = "2")]
    pub clue_public_key: ::prost::alloc::vec::Vec<u8>,
    /// Schnorr signature (darkfi-serial) over:
    ///    b"DarkFi-UnifOMR-CluePK-v2" || network_byte || key_version (u64 LE)
    ///      || payment_pubkey || clue_public_key
    /// under the payment SecretKey. Required — proves ownership of payment_pubkey,
    /// binds the network (no cross-network replay) and a monotonic key_version
    /// (no stale-registration replay / clue-key pinning).
    #[prost(bytes = "vec", tag = "3")]
    pub ownership_proof: ::prost::alloc::vec::Vec<u8>,
    /// Client-chosen monotonic version (unix seconds). The server only replaces
    /// an existing registration when key_version is strictly greater.
    #[prost(uint64, tag = "4")]
    pub key_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CluePublicKey {
    #[prost(bytes = "vec", tag = "1")]
    pub clue_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub found: bool,
    /// Directory attestation (fixed padded wire length), signed by
    /// LightInfo.directory_attest_pubkey over:
    ///    b"DarkFi-UnifOMR-DirAttest-v1" || network || key_version || payment_pk || clue_pk
    /// Real and decoy entries both verify. Clients MUST verify this (not a
    /// payment-key Schnorr) before building a clue.
    #[prost(bytes = "vec", tag = "3")]
    pub ownership_proof: ::prost::alloc::vec::Vec<u8>,
    /// key_version from registration, or a plausible decoy timestamp.
    #[prost(uint64, tag = "4")]
    pub key_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchPirRequest {
    /// BFV ciphertexts: SealPIR-style striped selection (one CT per stripe) over \[start_height, end_height\].
    /// For multi-limb payloads, client sends one query CT per request (limb_index).
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub query_ciphertexts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Inclusive height window the selection vector indexes into (slot i = start_height + i).
    #[prost(uint32, tag = "2")]
    pub start_height: u32,
    #[prost(uint32, tag = "3")]
    pub end_height: u32,
    /// Which u64-limb of the compact-block serialization to retrieve (0-based).
    #[prost(uint32, tag = "4")]
    pub limb_index: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchPirResponse {
    /// BFV ciphertext(s) encrypting the selected limb(s) / packed payload fragments.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub payload_ciphertexts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Generated client implementations.
pub mod dark_fi_light_wallet_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct DarkFiLightWalletClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DarkFiLightWalletClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DarkFiLightWalletClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DarkFiLightWalletClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DarkFiLightWalletClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stream compact blocks in an inclusive height range [start, end].
        /// The server returns blocks in ascending height order.
        pub async fn get_block_range(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactBlock>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetBlockRange",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetBlockRange",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get a single compact block by height.
        pub async fn get_block(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockHeight>,
        ) -> std::result::Result<tonic::Response<super::CompactBlock>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("darkfi.lightwallet.DarkFiLightWallet", "GetBlock"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream compact blocks at specific heights (sparse fetch).
        /// Heights should be sorted unique; server sorts/dedups. Cap 512.
        /// Returns NOT_FOUND if any requested height is missing.
        pub async fn get_compact_blocks_at_heights(
            &mut self,
            request: impl tonic::IntoRequest<super::HeightList>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactBlock>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetCompactBlocksAtHeights",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetCompactBlocksAtHeights",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get the current chain tip height and hash.
        pub async fn get_chain_tip(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::ChainTip>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetChainTip",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetChainTip",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to new blocks as they are finalized.
        /// The server streams CompactBlock messages for each new block.
        pub async fn subscribe_blocks(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompactBlock>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/SubscribeBlocks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "SubscribeBlocks",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get a full transaction by its hash. Returns the serialized Transaction
        /// (including proofs and signatures, unlike compact blocks).
        pub async fn get_transaction(
            &mut self,
            request: impl tonic::IntoRequest<super::TxHash>,
        ) -> std::result::Result<tonic::Response<super::RawTransaction>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetTransaction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Phase 1: UnifOMR Detection (Linear Partial Decryption)
        /// Client streams the detection key(s) in ~1 MiB chunks, avoiding the need
        /// for a 160 MiB single-message gRPC limit.
        /// The first message MUST be a DetectionKeyChunk with header fields set.
        pub async fn get_unif_omr_digest(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::DetectionKeyChunk>,
        ) -> std::result::Result<
            tonic::Response<super::OmrDigestResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetUnifOmrDigest",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetUnifOmrDigest",
                    ),
                );
            self.inner.client_streaming(req, path, codec).await
        }
        /// Phase 2: Batch PIR Fetch (Non-Linear Payload Retrieval)
        pub async fn fetch_pir_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchPirRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchPirResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/FetchPirBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "FetchPirBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Submit a signed transaction to the network via the backing darkfid node.
        pub async fn send_transaction(
            &mut self,
            request: impl tonic::IntoRequest<super::RawTransaction>,
        ) -> std::result::Result<tonic::Response<super::SendResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/SendTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "SendTransaction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Register an FHE OMR clue for a pending transaction (sender-side).
        /// lightwalletd merges this into CompactOutput.omr_clue when the tx confirms.
        pub async fn register_omr_clue(
            &mut self,
            request: impl tonic::IntoRequest<super::OmrClueRegistration>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/RegisterOmrClue",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "RegisterOmrClue",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get all note commitments (coins) added in a block range.
        pub async fn get_note_commitments(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::NoteCommitmentUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetNoteCommitments",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetNoteCommitments",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get all nullifiers revealed in a block range.
        pub async fn get_nullifiers(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::NullifierUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetNullifiers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetNullifiers",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get the Merkle tree state snapshot at a given height.
        pub async fn get_tree_state(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockHeight>,
        ) -> std::result::Result<tonic::Response<super::TreeState>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetTreeState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetTreeState",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Lookup zkas bincodes for a given contract ID.
        pub async fn lookup_zkas(
            &mut self,
            request: impl tonic::IntoRequest<super::ContractId>,
        ) -> std::result::Result<tonic::Response<super::ZkasResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/LookupZkas",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("darkfi.lightwallet.DarkFiLightWallet", "LookupZkas"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get server OMR capabilities (scheme is always "unifomr" when enabled).
        pub async fn get_omr_capabilities(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::OmrCapabilities>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetOmrCapabilities",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetOmrCapabilities",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Publish the wallet's UnifOMR RLWE clue public key (pk_clue), keyed by
        /// payment pubkey hash. Senders look this up before GenClue.
        pub async fn register_clue_public_key(
            &mut self,
            request: impl tonic::IntoRequest<super::CluePublicKeyRegistration>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/RegisterCluePublicKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "RegisterCluePublicKey",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Fetch a recipient's UnifOMR clue public key by payment pubkey (32 bytes).
        pub async fn get_clue_public_key(
            &mut self,
            request: impl tonic::IntoRequest<super::PaymentPubkey>,
        ) -> std::result::Result<tonic::Response<super::CluePublicKey>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetCluePublicKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetCluePublicKey",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get server metadata: version, chain info, sync status.
        pub async fn get_light_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::LightInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/darkfi.lightwallet.DarkFiLightWallet/GetLightInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "darkfi.lightwallet.DarkFiLightWallet",
                        "GetLightInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
